create schema if not exists aftora_crm;

create table if not exists aftora_crm.dealers (id bigint generated always as identity primary key, name text not null, legal_name text, inn text, city text, region text, discount_rate numeric not null default 0, contact_email text, contact_phone text, manager_id bigint, notes text, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists aftora_crm.outlets (id bigint generated always as identity primary key, dealer_id bigint references aftora_crm.dealers(id), name text not null, address text, city text, phone text, created_at timestamptz not null default now());
create table if not exists aftora_crm.profiles (id bigint generated always as identity primary key, user_id uuid unique, email text not null unique, full_name text not null, phone text, role text not null default 'dealer_admin', dealer_id bigint references aftora_crm.dealers(id), outlet_id bigint references aftora_crm.outlets(id), status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists aftora_crm.collections (id bigint generated always as identity primary key, name text not null, description text, price_tier text not null default 'standard', created_at timestamptz not null default now());
create table if not exists aftora_crm.products (id bigint generated always as identity primary key, collection_id bigint references aftora_crm.collections(id), collection_name text, name text not null, model_code text, material text, finish text, width_options text, height_options text, color_options text, glass boolean not null default false, base_price numeric not null default 0, stock_status text not null default 'in_stock', production_days integer not null default 7, specs jsonb not null default '{}'::jsonb, image_url text, created_at timestamptz not null default now());
create table if not exists aftora_crm.orders (id bigint generated always as identity primary key, order_number text unique not null, dealer_id bigint references aftora_crm.dealers(id), dealer_name text, outlet_id bigint references aftora_crm.outlets(id), created_by text, created_by_name text, status text not null default 'submitted', total_amount numeric not null default 0, comment text, requested_delivery_date date, confirmed_at timestamptz, ready_at timestamptz, shipped_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists aftora_crm.order_items (id bigint generated always as identity primary key, order_id bigint not null references aftora_crm.orders(id) on delete cascade, product_id bigint references aftora_crm.products(id), product_name text, model_code text, width text, height text, color text, glass boolean not null default false, quantity integer not null default 1, unit_price numeric not null default 0, is_custom boolean not null default false, custom_spec text, created_at timestamptz not null default now());
create table if not exists aftora_crm.status_log (id bigint generated always as identity primary key, order_id bigint not null references aftora_crm.orders(id) on delete cascade, status text not null, changed_by text, note text, created_at timestamptz not null default now());
create table if not exists aftora_crm.tickets (id bigint generated always as identity primary key, ticket_number text unique not null, dealer_id bigint references aftora_crm.dealers(id), dealer_name text, created_by text, created_by_name text, subject text not null, category text not null default 'other', priority text not null default 'medium', status text not null default 'open', description text, ai_response text, ai_resolved boolean not null default false, escalated boolean not null default true, ai_conversation_id bigint, assigned_to text, resolution text, resolved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists aftora_crm.ticket_messages (id bigint generated always as identity primary key, ticket_id bigint not null references aftora_crm.tickets(id) on delete cascade, author_email text, author_role text not null, author_name text, message text not null, created_at timestamptz not null default now());
create table if not exists aftora_crm.claims (id bigint generated always as identity primary key, claim_number text unique not null, dealer_id bigint references aftora_crm.dealers(id), dealer_name text, order_id bigint references aftora_crm.orders(id), order_number text, created_by text, created_by_name text, product_name text, defect_type text, description text, quantity integer not null default 1, status text not null default 'submitted', resolution text, compensation_amount numeric, assigned_to text, resolved_at timestamptz, created_at timestamptz not null default now());
create table if not exists aftora_crm.knowledge_base (id bigint generated always as identity primary key, title text not null, category text, content text not null, tags text, views integer not null default 0, helpful integer not null default 0, created_by text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists aftora_crm.activity_log (id bigint generated always as identity primary key, user_email text, user_name text, action text not null, entity_type text, entity_id bigint, details text, created_at timestamptz not null default now());
create table if not exists aftora_crm.notifications (id bigint generated always as identity primary key, user_email text, target_role text, title text not null, message text not null, type text not null default 'info', related_id bigint, read boolean not null default false, created_at timestamptz not null default now());
create table if not exists aftora_crm.training_modules (id bigint generated always as identity primary key, title text not null, category text, description text, content text, duration_min integer not null default 10, order_index integer not null default 0, created_at timestamptz not null default now());
create table if not exists aftora_crm.training_progress (id bigint generated always as identity primary key, user_email text not null, module_id bigint not null references aftora_crm.training_modules(id) on delete cascade, status text not null default 'in_progress', score numeric, completed_at timestamptz, unique(user_email, module_id));
create table if not exists aftora_crm.ai_conversations (id bigint generated always as identity primary key, user_email text not null, messages jsonb not null default '[]'::jsonb, intent text, resolved boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists orders_dealer_id_idx on aftora_crm.orders(dealer_id);
create index if not exists tickets_dealer_id_idx on aftora_crm.tickets(dealer_id);
create index if not exists claims_dealer_id_idx on aftora_crm.claims(dealer_id);
